name: Advanced CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 18

  test:
    runs-on: ubuntu-latest
    needs: call-build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/

      - name: Show Artifact
        run: cat dist/output.txt

      - name: Run Tests
        run: echo "Tests Passed"

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/

      - name: Create Package
        run: tar -czf app.tar.gz dist

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: production-package
          path: app.tar.gz